feat: update yq from v3 to v4

diff --git a/k8s-cluster-export b/k8s-cluster-export
--- a/k8s-cluster-export
+++ b/k8s-cluster-export
@@ -1,11 +1,11 @@
 #!/bin/bash
 # 
 # k8s-cluster-export
-# Modified:  2019-10-31
+# Modified:  2022-11-06
 # purpose:   move kubernetes resources to an other cluster
 #            (and if requested import to an other namespace)
 # 
-# Modified by Michael Zervakis m.zervakis@infinitum.gr
+# Modified by Thibaud B. https://github.com/ingvaar
 #
 # forked from https://github.com/tmattausch/k8s-cluster-export
 # author:    Thomas Mattausch (thomas@mattausch.org) 
@@ -51,13 +51,10 @@ available_cluster_resources=(
 
 display_help() {
 echo "
-USAGE: k8s-export.sh {-n namespace [-c new-namespace] | -g} [-h] [-k kubeconfig] [-r resource-1] [-r resource-2] [-i inputfile (e.g. deploy)] [-i pvc]
-
+USAGE: k8s-export.sh -n namespace [-h] [-r resource-1] [-r resource-2] [-c new-namespace] [-i inputfile (e.g. deploy)] [-i pvc]
 description     This script will export kubernetes resource configs the exported resources can be 
                 limited with -r to a specefic resource type (e.g. -r pvc -r sv).
-
                 And can be limited with -i to a subset of resources in that namespace.
-
                 parameter:
                 -n:   set source to namespace
                 -g:   set source to cluster 
@@ -65,9 +62,7 @@ description     This script will export kubernetes resource configs the exported
                 -i:   limit exported resources to input file (new line serparted)
                       the input file must match the name of the resource (can be repeated multiple times)
                 -c:   change namespace to specified value
-                -k:   path to kubectl kubeconfig file
                 By not setting -r all resources will be exported.
-
 Supported Namespaced Resources:
 "
 printf '%s\n' "${available_resources[@]}"
@@ -77,7 +72,7 @@ Supported Cluster Resources:
 printf '%s\n' "${available_cluster_resources[@]}"
 }
 
-while getopts ':n:r:i:c:k:gh' opt; do
+while getopts ':n:r:i:c:gh' opt; do
     case "$opt" in
         r) manual_resource+=("$OPTARG") ;;
         n) if [ -n "$CLUSTER" ]; then
@@ -95,13 +90,6 @@ while getopts ':n:r:i:c:k:gh' opt; do
            else
              CLUSTER=1
            fi             
-           ;;
-        k) if [ ! -f $OPTARG ]; then
-             echo "Kube Config File $OPTARG not found" >&2
-             exit 1
-           else
-             KUBECONFIG=$OPTARG
-           fi
            ;;
         h) display_help
            exit 0 ;;
@@ -143,13 +131,13 @@ function main {
 
 function export_config {
   export_resources=("$@")
-  [ $TERM != "dumb" ] && echo -e "\n${BLUE}⎈ ⎈ ☃ ⎈ ⎈\n${NC}"
+  echo -e "\n${BLUE}⎈ ⎈ ☃ ⎈ ⎈\n${NC}"
   status_output "start export resources for ns $NAMESPACE" "step"
 
   if [ -n "$NAMESPACE" ]; then
     mkdir -p $SOURCE/$NAMESPACE
   else
-    mkdir -p $SOURCE/CLUSTER
+    mkdir -p $SOURCE/cluster
   fi
   
   for r in "${export_resources[@]}"; do
@@ -160,15 +148,13 @@ function export_config {
 function set_env {
   pv_target=()
   SOURCE="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
-  if [ $TERM != "dumb" ]; then
-    BLUE='\033[1;34m'
-    GREEN='\033[1;32m'
-    RED='\033[0;31m'
-    YELLOW='\033[1;33m'
-    NC='\033[0m' # No Color
-    BOLD=$(tput bold)
-    NORMAL=$(tput sgr0)
-  fi
+  BLUE='\033[1;34m'
+  GREEN='\033[1;32m'
+  RED='\033[0;31m'
+  YELLOW='\033[1;33m'
+  NC='\033[0m' # No Color
+  BOLD=$(tput bold)
+  NORMAL=$(tput sgr0)
 }
 
 function status_output {
@@ -178,28 +164,21 @@ function status_output {
   elif [ $2 == "warn" ]; then
     echo -e "${YELLOW}-------------- $1 --------------${NC}"
   elif [ $2 == "error" ]; then
-    echo -e "${RED}ERROR: $1${NC}"
+     echo -e "${RED}ERROR: $1${NC}"
   elif [ $2 == "step" ]; then
     echo -e "${BOLD}---- $1 ----${NORMAL}"
   else
-    echo -e "${RED}ERROR in status_output$1${NC}"
-    exit 1
+     echo -e "${RED}ERROR in status_output$1${NC}"
+     exit 1
   fi
   echo -e ""
 }
 
 function check_prerequisites {
   #check kubectl installation
-  if [ ! -x "$(command -v kubectl)" ]; then
+  if [ ! -x "$(command -v kubectl)" ] ; then
     status_output "kubectl is not instaled" "error"
     exit 1
-  fi
-  
-  ## Set Kubectl Config
-  if [ -n "$KUBECONFIG" ]; then
-     KUBECTL="kubectl --kubeconfig=$KUBECONFIG"
-  else
-     KUBECTL="kubectl"
   fi
 
   #check if namespace parameter is set
@@ -210,7 +189,7 @@ function check_prerequisites {
   fi
 
   #check if namespace exists
-  if ${KUBECTL} get ns $NAMESPACE; then
+  if kubectl get ns $NAMESPACE; then
     :
   else
     status_output "namespace not valid ($NAMESPACE)" "error"
@@ -245,26 +224,26 @@ function check_manual_resource {
 
 function show_diff {
   status_output "changes" "warn"
-  if [ -x "$(command -v colordiff)" ] && [ -n $TERM ]; then
-    colordiff -y --suppress-common-lines $RAW $RESULT || true
+  if [ ! -x "$(command -v colordiff)" ] ; then
+    diff -y $RAW $RESULT || true
   else
-    diff --color=never -y $RAW $RESULT || true
+    colordiff -y --suppress-common-lines $RAW $RESULT || true
   fi
 }
 
 function remove_yaml_value {
   arr=("$@")
   for i in "${arr[@]}"; do
-    yq d -i $RESULT $i
+    yq -i "del(.$i)" $RESULT
   done
 }
 
 function change_namespace {
   if [ -n "$NEW_NAMESPACE" ]; then
     if [ $TYPE == "pv" ]; then
-      yq w -i $RESULT spec.claimRef.namespace $NEW_NAMESPACE
+      yq -i ".spec.claimRef.namespace = $NEW_NAMESPACE" $RESULT
     else
-      yq w -i $RESULT metadata.namespace $NEW_NAMESPACE
+      yq -i ".metadata.namespace = $NEW_NAMESPACE" $RESULT
     fi
   fi
 }
@@ -279,9 +258,9 @@ function set_targets {
       targets+=("$line")
     done <$1
   elif [ -n "$NAMESPACE" ]; then
-    targets=($(${KUBECTL} get $1 -n ${NAMESPACE} --no-headers -o=custom-columns=NAME:.metadata.name ))
+    targets=($(kubectl get $1 -n ${NAMESPACE} --no-headers -o=custom-columns=NAME:.metadata.name ))
   else
-    targets=($(${KUBECTL} get $1 --no-headers -o=custom-columns=NAME:.metadata.name ))
+    targets=($(kubectl get $1 --no-headers -o=custom-columns=NAME:.metadata.name ))
   fi
 }
 
@@ -289,11 +268,11 @@ function set_targets {
 function remove_status {
   # reset status
   if [[ " (pvc deploy quota limits job) " =~ " $TYPE " ]]; then
-    yq d -i $RESULT status ; echo 'status: {}' >> $RESULT
+    yq -i "del(.$status)" $RESULT ; echo 'status: {}' >> $RESULT
   elif [ $TYPE == "sts" ]; then
-    yq d -i $RESULT status ; echo -e 'status:\n  replicas: 0' >> $RESULT
+    yq -i "del(.$status)" $RESULT ; echo -e 'status:\n  replicas: 0' >> $RESULT
   elif [ $TYPE == "svc" ] || [ $TYPE == "ing" ]; then
-    yq d -i $RESULT status ; echo -e 'status:\n  loadBalancer: {}' >> $RESULT
+    yq -i "del(.$status)" $RESULT ; echo -e 'status:\n  loadBalancer: {}' >> $RESULT
   fi
 }
 
@@ -307,8 +286,8 @@ function export_resource {
     mkdir -p $SOURCE/$NAMESPACE/$2_$1
     TARGET_FOLDER="$SOURCE/$NAMESPACE/$2_$1"
   else
-    mkdir -p $SOURCE/CLUSTER/$2_$1
-    TARGET_FOLDER="$SOURCE/CLUSTER/$2_$1"
+    mkdir -p $SOURCE/cluster/$2_$1
+    TARGET_FOLDER="$SOURCE/cluster/$2_$1"
   fi
 
   for i in "${targets[@]}"; do
@@ -322,15 +301,15 @@ function export_resource {
       status_output "no value set skip export for $TYPE $i" "warn"
     else
       # export resource and adjust the output
-      ${KUBECTL} get $TYPE $i -o yaml ${kubectl_namespace} > $RAW
+      kubectl get $TYPE $i -o yaml ${kubectl_namespace} > $RAW
       cp $RAW $RESULT
       remove_yaml_value "${remove[@]}"
       # only export PVs for correspoinding PVCs
       if [ "$1" = "pvc" ]; then
-        pv_targets+=($(yq r $RESULT spec.volumeName))
+        pv_targets+=($(yq ".spec.volumeName" $RESULT))
       # change generation to 1 for sts
       elif [ "$1" = "sts" ]; then
-        yq w -i $RESULT metadata.generation 1
+        yq -i '.metadata.generation = 1' $RESULT
       fi
       change_namespace
       remove_status
@@ -396,7 +375,7 @@ function svc {
   remove=(
     ${objectmeta_v1[@]}
     "spec.clusterIP"
-    "spec.ports.*.nodePort"
+    "spec.ports.[].nodePort"
   )
   export_resource "svc" "07" "${remove[@]}"
 }
